// <auto-generated />
namespace FlightTracking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1stMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1stMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101226316_1stMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
